### PR TITLE
Port gene set functionality from cBioPortal pull requests

### PR DESCRIPTION
**Pull request by fedde-s**
This ports the changes made to the Oncoprint rendering code by the various previously reviewed pull requests collected by cBioPortal/cbioportal#3319 to the OncoprintJS repository, as discussed there. The merge commits indicate where the changes have been reviewed in context. One additional commit demonstrates the functionality in the demo/test setup of the OncoprintJS project.

## Screencast ##

Screencast showcasing the expand button and expansion group behaviour in the demo Oncoprint, with misrendered track option buttons

## Structure ##

<details>
<summary>This log shows how the commits in the pull request relate to previous pull requests.</summary>

```
* cc3648d10 Demonstrate expansion API in the test setup
* 69287bde8 Fix track dragging below bottommost expansion
*   b03327408 Port changes from pull request thehyve/cbioportal#21
|\
| * 9e5dd1aeb Keep tracks from moving in/out of expansion groups
| * 2d4888262 Move a track's expansion tracks along with it
|/
*   b308f0ba0 Port changes from pull request thehyve/cbioportal#19
|\
| * 739659e1c Allow HTML versions of track names
| * c424ce59b Allow annotating Oncoprint tracks with a hyperlink
| * 3b55080af Make Oncoprint label view tooltips mouse-navigable
| * 41cb6588b Prevent HTML injection in Oncoprint track tooltips
|/
*   258a7b7e0 Port changes from pull request cBioPortal/cbioportal#2190
|\
| * a0c5334a1 Remove expansion tracks before clustering
| * 615f8cfc9 Add track expansion support to  Oncoprint classes
|/
*   a158948ca Port changes from pull request cBioPortal/cbioportal#2186
|\
| * 7e2453bcb Add gene set score heatmap tracks to the Oncoprint
|/
*
```
</details>

### CODE REVIEW

**Comment by fedde-s** [comment]
I rebased everything on the current state of the `master` branch to resolve conflicts, as requested elsewhere.

**Comment by fedde-s** [comment]
I currently can't seem to test my changes in rebased context because of issue #51.

**Comment by fedde-s** [comment]
I used the build process from Travis instead and `npm link`ed the project into my cBioPortal frontend checkout to test it, and found an issue: the `$makeDropdownOption()` function in `oncoprinttrackoptionsview.js` now expects a boolean indicating whether the option is disabled as the third parameter, *before* the pre-existing callback. I'll add one change to my patch: pass a ‘false’ in the two calls I added.

**Comment by adamabeshouse** [comment]
@fedde-s that doesn't seem like a major issue, right, just make sure all the calls use the right arguments?

**Comment by fedde-s** [comment]
Yeah, you're right. I played around with the API in a cBioPortal context and tested parameters that should be effectively identical to the ones I added to the demo: once the import issue there is fixed it should ‘just work’.

I squashed the PR into four commits which I believe to explain the independent new features I added, and rebased on the current state of the `master` branch.

**Comment by adamabeshouse** [comment]
thanks @fedde-s , let me talk to @alisman and company and see when would be a good time to merge this

**Comment by fedde-s** [comment]
It shouldn't break anything: it only adds new features that would not have any effect if not enabled in the parameters of some track, except for one minor thing: the feature to include hyperlinks in track label tooltips adjusts them not to disappear when the mouse hovers from the label onto the tooltip, in the same way I saw it implemented for cell view tooltips.

**Comment by fedde-s** [comment]
As discussed elsewhere, I added a small change to ensure that new expansion tracks are automatically inserted  underneath their parent track, rather than having to be reordered after adding the track. This makes the library's API a bit less non-obvious.

**Pull request merged**
