### PR TITLE
Negative value support for bar rule set

### PR DESCRIPTION
**Pull request by rnugraha**
This pull request is to add support of negative values when displaying clinical track in the OncoPrint tab. These changes will handle three possibilities:

### Data consists of non negative values
===
screen shot 2017-08-01 at 22 03 41

### Data consists of non positive values
===
screen shot 2017-08-01 at 22 04 13

### Data consists of all type of values
===
screen shot 2017-08-01 at 22 03 14

### CODE REVIEW

**Comment by fedde-s** [comment]
I understand that this is about the visualisation of all numeric clinical attributes. Did you test if it still works when:
- [ ]  all values are identical,
- [ ] there's only one sample (probably rare, but I see no reason to break it and having an edge-case there could hint at other problems),
- [ ] the values are all much larger than 20 / much smaller than -20, or
- [ ] the maximum and minimum are not integers?

I do not mean to require more functionality in this changeset beyond what it proposes to add, but to ensure that functionality already supported isn't broken by it.

**Comment by fedde-s** [comment]
Ah, the “all much larger/smaller” scenario is probably trivial, your all-negative screenshot shows that the baseline can scale away from 0.

**Comment by rnugraha** [comment]
@fedde-s I would be very happy if you can also help to test the the use cases you mentioned by using the test.js provided in the code. I can assist you on how to use it.

**Comment by fedde-s** [comment]
Do I read things correctly if I think that this functionality has already been released via cBioPortal/oncoprintjs#26?

**Comment by adamabeshouse** [comment]
this is definitely merged and live unless theres some other feature involved here

**Pull request closed without merging**
